root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  useJSXTextNode: true
extends:
  - prettier
plugins:
  - '@typescript-eslint'
rules:
  no-eval: error
  no-debugger: error
  no-console: error
  no-duplicate-imports: error
  no-var: error
  no-unsafe-finally: error
  no-restricted-imports: off
  prefer-const: error
  prefer-rest-params: error
  no-trailing-spaces:
    - error
    - ignoreComments: true
  '@typescript-eslint/no-use-before-define': error
  '@typescript-eslint/no-namespace': error
overrides:
  - files: '**/*.ts'
    excludedFiles: ['*.test.ts', '**/testing/**']
    rules:
      '@typescript-eslint/no-restricted-imports':
        - error
        - paths:
            - name: typescript
              message: "Use 'tsmodule' instead"
              allowTypeImports: true
