codecov:
  require_ci_to_pass: yes

ignore:
  - 'webpack.js'
  - 'addons/**/*'
  - 'project-fixtures/**/*'

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: no

parsers:
  javascript:
    enable_partials: yes
