/* The following types are extracted from index.ts */
/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { GqlURL } from "../types";
export type PostFragment = {
    title: string;
    body: string;
    publishedAt: Date;
    entryURL: GqlURL;
    ogImageURL: GqlURL;
};
