/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type RepositoryFragment = {
    description: string | null;
};
export type GitHubQuery = {
    viewer: {
        repositories: {
            nodes: (({
                id: string;
            } & RepositoryFragment) | null)[] | null;
        };
    };
};
export type GitHubQueryVariables = {
    first: number;
};
export type GitHubQueryDocument = TypedQueryDocumentNode<GitHubQuery, GitHubQueryVariables>;
