/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type UpdateMyRepository = {
    updateRepository: ({
        clientMutationId: string | null;
    }) | null;
};
export type UpdateMyRepositoryVariables = {
    repositoryId: string;
};
export type UpdateMyRepositoryDocument = TypedQueryDocumentNode<UpdateMyRepository, UpdateMyRepositoryVariables>;
