/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
export type UpdateMyRepository = {
    updateRepository: ({
        clientMutationId: string | null;
    }) | null;
};
export type UpdateMyRepositoryVariables = {
    repositoryId: string;
};
export type UpdateMyRepositoryDocument = TypedDocumentNode<UpdateMyRepository, UpdateMyRepositoryVariables>;
