name: publish

on:
  push:
    tags:
      - v*

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - id: dist-tag
        uses: actions/github-script@v9
        with:
          result-encoding: string
          script: |
            return /^refs\/tags\/v\d+\.\d+\.\d+$/.test(context.ref) ? "latest" : "next"

      - name: npm publish
        run: |
          npm ci
          npm run build
          npm publish --tag ${{ steps.dist-tag.outputs.result }}
        env:
          CI: true
